/**
 * Returns a random pair of different, yet somewhat similar words.
 */
export function getRandomWordPair(): [string, string] {
    const pair = pairs[Math.floor(Math.random() * pairs.length)];
    return Math.random() < 0.5 ? pair : [pair[1], pair[0]];
}

const pairs: [string, string][] = [
    ["Pizza", "Burger"],
    ["Mountain", "Valley"],
    ["Rainbow", "Cloud"],
    ["Guitar", "Drums"],
    ["Ocean", "Beach"],
    ["Coffee", "Tea"],
    ["Sky", "Star"],
    ["Sunset", "Sunrise"],
    ["Dolphin", "Whale"],
    ["Apple", "Orange"],
    ["Candle", "Lightbulb"],
    ["Rose", "Tulip"],
    ["Forest", "Jungle"],
    ["Moon", "Sun"],
    ["Brick", "Stone"],
    ["Train", "Airplane"],
    ["Doctor", "Nurse"],
    ["Radio", "TV"],
    ["Ghost", "Zombie"],
    ["Cat", "Dog"],
    ["Ice cream", "Cake"],
    ["Car", "Bicycle"],
    ["Helmet", "Hat"],
    ["Mountain", "Hill"],
    ["Butterfly", "Bee"],
    ["Laptop", "Desktop"],
    ["Rain", "Snow"],
    ["Glasses", "Sunglasses"],
    ["T-shirt", "Sweater"],
    ["Keyboard", "Mouse"],
    ["Plane", "Helicopter"],
    ["Train", "Bus"],
    ["Apricot", "Peach"],
    ["Piano", "Violin"],
    ["Rock", "Pop"],
    ["Mountain", "Cliff"],
    ["Sapphire", "Emerald"],
    ["Diamond", "Ruby"],
    ["Darkness", "Light"],
    ["Pineapple", "Mango"],
    ["Elephant", "Giraffe"],
    ["Camera", "Phone"],
    ["Swan", "Duck"],
    ["Bonsai", "Cactus"],
    ["Fish", "Shark"],
    ["Bread", "Bagel"],
    ["Salt", "Pepper"],
    ["Paper", "Plastic"],
    ["Sofa", "Chair"],
    ["Tree", "Flower"],
    ["Waterfall", "River"],
    ["Jetpack", "Rocket"],
    ["Helmet", "Goggles"],
    ["Pirate", "Ninja"],
    ["Rosemary", "Basil"],
    ["Soccer", "Basketball"],
    ["Bike", "Scooter"],
    ["Superman", "Batman"],
    ["Telescope", "Microscope"],
    ["Horse", "Cow"],
    ["Microphone", "Speaker"],
    ["Lion", "Tiger"],
    ["Sailboat", "Kayak"],
    ["Maze", "Puzzle"],
    ["Headphones", "Earbuds"],
    ["Raincoat", "Umbrella"],
    ["Surfboard", "Skateboard"],
    ["Gorilla", "Monkey"],
    ["Leaf", "Branch"],
    ["Penguin", "Seal"],
    ["Comedy", "Drama"],
    ["Computer", "Tablet"],
    ["Sushi", "Taco"],
    ["Winter", "Summer"],
    ["Dentist", "Orthodontist"],
    ["Bacon", "Eggs"],
    ["Hotel", "Motel"],
    ["Batman", "Joker"],
    ["Laptop", "Tablet"],
    ["Donut", "Croissant"],
    ["Mosquito", "Fly"],
    ["Camping", "Hiking"],
    ["Zebra", "Gazelle"],
    ["Pear", "Plum"],
    ["Cupcake", "Cookie"],
    ["Snowman", "Sandcastle"],
    ["Pancake", "Waffle"],
    ["Dove", "Pigeon"],
    ["Bridge", "Tunnel"],
    ["Chef", "Baker"],
    ["City", "Town"],
    ["Tea", "Coffee"],
    ["Rose", "Daisy"],
    ["School", "University"],
    ["Watermelon", "Cantaloupe"],
    ["Soccer", "Football"],
    ["Eagle", "Hawk"],
    ["Dolphin", "Shark"],
    ["Dragon", "Unicorn"],
    ["Rain", "Thunder"],
    ["Turtle", "Snail"],
    ["Lighthouse", "Lantern"],
    ["Cowboy", "Cowgirl"],
    ["Lemon", "Lime"],
    ["Spoon", "Fork"],
    ["Rose", "Lavender"],
    ["Pajamas", "Robe"],
    ["Bicycle", "Tricycle"],
    ["Fan", "Air conditioner"],
    ["Laptop", "Smartphone"],
    ["Baseball", "Football"],
    ["Lion", "Wolf"],
    ["Cappuccino", "Latte"],
    ["Panther", "Leopard"],
    ["Vampire", "Werewolf"],
    ["Pumpkin", "Corn"],
    ["Owl", "Eagle"],
    ["Broccoli", "Cauliflower"],
    ["Water", "Soda"],
    ["Sandal", "Sneaker"],
    ["Tennis", "Golf"],
    ["Chicken", "Rooster"],
    ["Coconut", "Pineapple"],
    ["Movie", "Theater"],
    ["Phone", "Tablet"],
    ["Bowling", "Billiards"],
    ["Berries", "Fruits"],
    ["Street", "Avenue"],
    ["Aquarium", "Zoo"],
    ["Tiger", "Leopard"],
    ["Candy", "Chocolates"],
    ["Giraffe", "Elephant"],
    ["Pencil", "Pen"],
    ["Fountain", "Waterfall"],
    ["Spaghetti", "Fettuccine"],
    ["Rose", "Magnolia"],
    ["Shower", "Bath"],
    ["Skiing", "Snowboarding"],
    ["Bathrobe", "Towel"],
    ["Pizza", "Pasta"],
    ["Cinnamon", "Nutmeg"],
    ["Snake", "Lizard"],
    ["Dancer", "Singer"],
    ["Coffee", "Espresso"],
    ["Penguin", "Polar bear"],
    ["Carrot", "Radish"],
    ["Pecan", "Walnut"],
    ["Llama", "Alpaca"],
    ["Butterfly", "Moth"],
    ["Crab", "Lobster"],
    ["Lamp", "Chandelier"],
    ["Banana", "Coconut"],
    ["Movie", "Popcorn"],
    ["Kangaroo", "Koala"],
    ["Rose", "Orchid"],
    ["Laptop", "Desktop"],
    ["Sushi", "Sashimi"],
    ["Tangerine", "Mandarin"],
    ["Horse", "Donkey"],
    ["Burger", "Hot dog"],
    ["Cherry", "Strawberry"],
    ["Sailboat", "Ship"],
    ["Thunder", "Lightning"],
    ["Pearl", "Diamond"],
    ["Beef", "Pork"],
    ["Car", "Truck"],
    ["Chocolate", "Vanilla"],
    ["Violin", "Cello"],
    ["Hiking", "Camping"],
    ["Seashell", "Starfish"],
    ["Train", "Subway"],
    ["Soccer", "Hockey"],
    ["Parrot", "Macaw"],
    ["Orange", "Grapefruit"],
    ["Tent", "RV"],
    ["Skyscraper", "Tower"],
    ["Mango", "Banana"],
    ["Anchor", "Boat"],
    ["Otter", "Beaver"],
    ["Necklace", "Bracelet"],
    ["T-shirt", "Tank top"],
    ["Mushroom", "Onion"],
    ["Sunflower", "Daisy"],
    ["Compass", "Map"],
    ["Backpack", "Suitcase"],
    ["Bread", "Roll"],
    ["Tuna", "Salmon"],
    ["Lobster", "Shrimp"],
    ["Leaves", "Petals"],
    ["Eiffel Tower", "Statue of Liberty"],
    ["Cactus", "Succulent"],
    ["Squirrel", "Chipmunk"],
    ["Taco", "Burrito"],
    ["Sofa", "Couch"],
    ["Ostrich", "Emu"],
    ["Rugby", "Football"],
    ["Panda", "Koala"],
    ["Grape", "Blueberry"],
    ["Carpet", "Tile"],
    ["Piano", "Guitar"],
    ["Caramel", "Butterscotch"],
    ["Skiing", "Ice skating"],
    ["Table", "Chair"],
    ["Sapphire", "Diamond"],
    ["Lion", "Jaguar"],
    ["Pineapple", "Banana"],
    ["Cheese", "Crackers"],
    ["Racecar", "Motorcycle"],
    ["Sunglasses", "Goggles"],
    ["Sunflower", "Rose"],
    ["Tulip", "Daisy"],
    ["Owl", "Crow"],
    ["Swimming", "Diving"],
    ["Bicycle", "Motorbike"],
    ["Bulldog", "Poodle"],
    ["Cupcake", "Muffin"],
    ["Ferrari", "Lamborghini"],
    ["Dolphin", "Seal"],
    ["Lion", "Bear"],
    ["Mango", "Papaya"],
    ["Pancake", "Crepe"],
    ["Skiing", "Snowmobiling"],
    ["Pumpkin", "Squash"],
    ["Ballet", "Tap dance"],
    ["Tortoise", "Turtle"],
    ["Peanut butter", "Jelly"],
    ["Strawberry", "Raspberry"],
    ["Coffee", "Cappuccino"],
    ["Caterpillar", "Butterfly"],
    ["Rose", "Peony"],
    ["Soccer", "Rugby"],
    ["Horse", "Pony"],
    ["Pear", "Apple"],
    ["Hot chocolate", "Tea"],
    ["Cucumber", "Zucchini"],
    ["Hiking", "Running"],
    ["Shampoo", "Conditioner"],
    ["Cherry", "Apple"],
    ["Sailboat", "Catamaran"],
    ["Diamond", "Emerald"],
    ["Bacon", "Sausage"],
    ["Pizza", "Calzone"],
    ["Cinnamon", "Clove"],
    ["Eagle", "Falcon"],
    ["Skiing", "Sledding"],
    ["T-shirt", "Hoodie"],
    ["Tomato", "Pepper"],
    ["Sunflower", "Dandelion"],
    ["Football", "Basketball"],
    ["Banana", "Plantain"],
    ["Guitar", "Bass"],
    ["Lion", "Cheetah"],
    ["Carrot", "Sweet potato"],
    ["Bread", "Baguette"],
    ["Salmon", "Trout"],
    ["Lobster", "Crab"],
    ["Cactus", "Palm tree"],
    ["Squirrel", "Sloth"],
    ["Bike", "Scooter"],
    ["Leopard", "Panther"],
    ["Shark", "Octopus"],
    ["Soccer", "Tennis"],
    ["Polar bear", "Grizzly bear"],
    ["Mushroom", "Mozzarella"],
    ["Grape", "Watermelon"],
    ["Skiing", "Snowboarding"],
    ["Cat", "Lion"],
    ["Pearl", "Opal"],
    ["Beef", "Chicken"],
    ["Ferris wheel", "Roller coaster"],
    ["Train", "Carriage"],
    ["Acorn", "Pinecone"],
    ["Sushi", "Tempura"],
    ["Penguin", "Puffin"],
    ["Blanket", "Comforter"],
    ["Tangerine", "Orange"],
    ["Horse", "Unicorn"],
    ["Burger", "Fries"],
    ["Cherry", "Plum"],
    ["Sailboat", "Speedboat"],
    ["Thunderstorm", "Blizzard"],
    ["Emerald", "Ruby"],
    ["Chicken", "Turkey"],
    ["Chocolate", "Caramel"],
    ["Flute", "Clarinet"],
    ["Hiking", "Climbing"],
    ["Starfish", "Seahorse"],
    ["Soccer", "Hockey"],
    ["Peacock", "Flamingo"],
    ["Peach", "Nectarine"],
    ["Jellyfish", "Stingray"],
    ["Bread", "Toast"],
    ["Salmon", "Shrimp"],
    ["Zucchini", "Eggplant"],
    ["Panda", "Bear"],
    ["Lion", "Leopard"],
    ["Mango", "Coconut"],
    ["Pancake", "Waffle"],
    ["Skiing", "Snowshoeing"],
    ["Pumpkin", "Gourd"],
    ["Ballet", "Belly dance"],
    ["Peanut butter", "Nutella"],
    ["Strawberry", "Blackberry"],
    ["Spider", "Scorpion"],
    ["Rose", "Lily"],
    ["Pear", "Grape"],
    ["Tea", "Milk"],
    ["Watermelon", "Melon"],
    ["Hiking", "Walking"],
    ["Shampoo", "Body wash"],
    ["Cherry", "Grape"],
    ["Sailboat", "Yacht"],
    ["Rain", "Snow"],
    ["Diamond", "Sapphire"],
    ["Bacon", "Ham"],
    ["Pizza", "Pita"],
    ["Cinnamon", "Ginger"],
    ["Eagle", "Owl"],
    ["Skiing", "Ice hockey"],
    ["T-shirt", "Shirt"],
    ["Potato", "Onion"],
    ["Sunflower", "Tulip"],
    ["Soccer", "Basketball"],
    ["Banana", "Kiwi"],
    ["Guitar", "Ukulele"],
    ["Lion", "Tiger"],
    ["Sailing", "Kayaking"],
    ["Bread", "Rolls"],
    ["Hamburger", "Veggie burger"],
    ["Cactus", "Succulent garden"],
    ["Squirrel", "Raccoon"],
    ["Bike", "Motorcycle"],
    ["Leopard", "Cheetah"],
    ["Shark", "Whale"],
    ["Rose", "Daffodil"],
    ["Soccer", "Volleyball"],
    ["Polar bear", "Panda"],
    ["Mushroom", "Portobello"],
    ["Watermelon", "Cantaloupe"],
    ["Desk", "Chair"],
    ["Pearl", "Diamond"],
    ["Beef", "Fish"],
    ["Ferris wheel", "Carousel"],
    ["Acorn", "Chestnut"],
    ["Lettuce", "Kale"],
    ["Blanket", "Quilt"],
    ["Tangerine", "Clementine"],
    ["Horse", "Pegasus"],
    ["Burger", "Onion rings"],
    ["Thunderstorm", "Tornado"],
    ["Emerald", "Topaz"],
    ["Chicken", "Beef"],
    ["Flute", "Saxophone"],
    ["Hiking", "Rafting"],
    ["Starfish", "Jellyfish"],
    ["Soccer", "Baseball"],
    ["Peacock", "Peahen"],
    ["Peach", "Apricot"],
    ["Jellyfish", "Sea anemone"],
    ["Backpack", "Knapsack"],
    ["Bread", "Bagel"],
    ["Salmon", "Tuna"],
    ["Zucchini", "Squash"],
    ["Panda", "Red panda"],
    ["Lion", "Bear"],
    ["Mango", "Pineapple"],
    ["Pancake", "French toast"],
    ["Skiing", "Cross-country skiing"],
    ["Pumpkin", "Jack-o'-lantern"],
    ["Ballet", "Hip hop"],
    ["Turtle", "Tortoise"],
    ["Peanut butter", "Almond butter"],
    ["Spider", "Centipede"],
    ["Rose", "Rosemary"],
    ["Soccer", "Tennis"],
    ["Pear", "Peach"],
    ["Tea", "Coffee"],
    ["Car", "Minivan"],
    ["Watermelon", "Pineapple"],
    ["Hiking", "Backpacking"],
    ["Shampoo", "Shower gel"],
    ["Cherry", "Cherry pie"],
    ["Sailboat", "Raft"],
    ["Rain", "Drizzle"],
    ["Diamond", "Pearl"],
    ["Bacon", "Canadian bacon"],
    ["Pizza", "Pepperoni"],
    ["Cinnamon", "Nutmeg"],
    ["Eagle", "Hawk"],
    ["Skiing", "Figure skating"],
    ["T-shirt", "Polo shirt"],
    ["Potato", "Sweet potato fries"],
    ["Sunflower", "Daisy"],
    ["Soccer", "Golf"],
    ["Computer", "Tablet"],
    ["Banana", "Coconut"],
    ["Guitar", "Piano"],
    ["Lion", "Jaguar"],
    ["Sailing", "Canoeing"],
    ["Carrot", "Radish"],
    ["Bread", "Loaf"],
    ["Salmon", "Crab"],
    ["Hamburger", "Chicken burger"],
    ["Lobster", "Shrimp cocktail"],
    ["Cactus", "Desert"],
    ["Squirrel", "Deer"],
    ["Coke", "Sprite"],
    ["Bike", "Rollerblades"],
    ["Leopard", "Tiger"],
    ["Shark", "Dolphin"],
    ["Rose", "Iris"],
    ["Soccer", "Rugby"],
    ["Polar bear", "Walrus"],
    ["Mushroom", "Truffle"],
    ["Watermelon", "Honeydew"],
    ["Desk", "Bookshelf"],
    ["Cat", "Kitten"],
    ["Pearl", "Amethyst"],
    ["Beef", "Pork"],
    ["Ferris wheel", "Ferris Bueller"],
    ["Train", "Steam engine"],
    ["Acorn", "Oak tree"],
    ["Sushi", "California roll"],
    ["Lettuce", "Romaine"],
    ["Penguin", "Arctic tern"],
    ["Blanket", "Throw"],
    ["Tangerine", "Blood orange"],
    ["Horse", "Steed"],
    ["Burger", "Cheeseburger"],
    ["Cherry", "Maraschino cherry"],
    ["Sailboat", "Pirate ship"],
    ["Thunderstorm", "Hurricane"],
];
